# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 123ee30f5e308c7b02bec1b9834431f786b715e5fc5d544f8f3c0834e694d3402d8efbe7ed5261d8cc53370f6c5e1f935b984d80897af4ea34a3a6614a650b82

test:
  secret_key_base: 0f4ec57053a1aefb8b0b0232c70d52af5bf94cfcebae297d1fcdf0c4cac825379a4a5700e485dca7722016292a4daa08645bf35df4c7d0736f66f3412bc6a02c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
